### PR TITLE
Bump version to 0.33.17

### PR DESCRIPTION
**Pull request by nalimilan**
Maybe let's merge https://github.com/JuliaStats/StatsBase.jl/pull/801 and https://github.com/JuliaStats/StatsBase.jl/pull/805 and then tag?

### CODE REVIEW

**Comment by ararslan** [comment]
I don't understand how this failure could only happen on nightly. The code was introduced in #499, and I guess nightly was failing for unrelated reasons back when that was merged, so it's possible that a nightly-specific issue with the PR wasn't caught.
```
ERROR: LoadError: MethodError: no method matching direct_sample!(::UnitRange{Int64}, ::Vector{Float64}, ::Matrix{Int64})
Closest candidates are:
  direct_sample!(::UnitRange, ::AbstractArray) at ~/work/StatsBase.jl/StatsBase.jl/src/sampling.jl:26
  direct_sample!(::AbstractRNG, ::AbstractArray, ::AbstractArray) at ~/work/StatsBase.jl/StatsBase.jl/src/sampling.jl:36
  direct_sample!(::AbstractArray, ::AbstractWeights, ::AbstractArray) at ~/work/StatsBase.jl/StatsBase.jl/src/sampling.jl:589
  ...
Stacktrace:
 [1] top-level scope
   @ ~/work/StatsBase.jl/StatsBase.jl/test/wsampling.jl:47
 [2] include(fname::String)
   @ Base.MainInclude./client.jl:472
 [3] top-level scope
   @ ~/work/StatsBase.jl/StatsBase.jl/test/runtests.jl:34
 [4] include(fname::String)
   @ Base.MainInclude./client.jl:472
 [5] top-level scope
   @ none:6
in expression starting at /home/runner/work/StatsBase.jl/StatsBase.jl/test/wsampling.jl:40
in expression starting at /home/runner/work/StatsBase.jl/StatsBase.jl/test/runtests.jl:31
```

**Comment by nalimilan** [comment]
That's https://github.com/JuliaLang/julia/issues/45511, as on master promotion transforms weights vectors of different types into `Vector{Float64}`. It seems it's going to be reverted so probably not worth changing.

**Comment by devmotion** [comment]
It seemed simple enough to fix the tests (and it will be correct even if the change in base is reverted), so I opened a PR: https://github.com/JuliaStats/StatsBase.jl/pull/807

**Comment by devmotion** [comment]
Good to go it seems? :slightly_smiling_face:

**Review by ararslan — APPROVED** [review]

**Pull request merged**
