### PR TITLE
Fixes some inbound errors

### PR DESCRIPTION
**Pull request by itsdebartha**
- Addresses #638
- Added tests

### CODE REVIEW

**Comment by ParadaCarleton** [comment]
This is great, thank you so much! Can you add tests for OffsetArrays to make sure this covers everything?

**Comment by itsdebartha** [comment]
@ParadaCarleton I have already added them. If you want, I can add more OffsetArrays tests. Let me know if I should...

**Comment by ParadaCarleton** [comment]
> @ParadaCarleton I have already added them. If you want, I can add more OffsetArrays tests. Let me know if I should...

Oh, you're right! I missed that `a` and `b` are defined as OffsetArrays in the tests.

**Comment by itsdebartha** [comment]
Yup, thanks...

**Comment by ararslan** [comment]
Closed and reopened to pull in the changes that fixed CI on Julia nightly.

**Pull request merged**
