### PR TITLE
Codecov: set `fail_ci_if_error` to `false` iff the PR is made from a fork

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@devmotion What do you think of this approach?

**Comment by devmotion** [comment]
I think this might be useful given the current instability of codecov. I'd like to avoid surprising coverage drops in PRs from forks though - maybe if someone with admin permission additionally makes codecov a mandatory check, this would not be possible? On the other hand, of course, this would require that at least one of the codecov uploads succeeds.

**Comment by DilumAluthge** [comment]
You could set up GitHub Merge Queue on this repo, and then make Codecov a required status check. The GitHub Merge Queue jobs (`merge_group` jobs) will have access to the `CODECOV_TOKEN`.

**Comment by andreasnoack** [comment]
Hasn't the Codecov action stabilized so much at this point that it's not worth adding extra complexity to our script?

**Pull request closed without merging**
