### PR TITLE
add replace and ordered keywords for sample! method (#633)

### LINKED ISSUE #633: sample! missing a method
```
using StatsBase, Random
sample!(1:10, zeros(5); replace=false)  # fine
sample!(1:10, Weights(rand(10)), zeros(5))  # fine
sample!(1:10, Weights(rand(10)), zeros(5); replace=false)  # no method!
sample!(Random.GLOBAL_RNG, 1:10, Weights(rand(10)), zeros(5); replace=false)  # fine 
```

Should be an easy fix. Shall I make a pull request?

### PR DESCRIPTION
**Pull request by fredcallaway**
Fixes #633

### CODE REVIEW

**Comment by fredcallaway** [comment]
The failures on nightly are in histograms, I assume not related to this patch. I can add a test case if that's desired, but it seems unnecessary given the simplicity of the change.

**Comment by nalimilan** [comment]
Thanks. Can you add tests that cover the new arguments?

**Comment by fredcallaway** [comment]
@nalimilan those look okay?

**Comment by nalimilan** [comment]
Thanks, and sorry for the delay!

**Pull request merged**
