### PR TITLE
Add badges for 0.7 and 1.0

### PR DESCRIPTION
**Pull request by oxinabox**
Is pkg.julialang.org working?
Lets find out (by checking the preview before merging)

### CODE REVIEW

**Comment by oxinabox** [comment]
Answer:
Not really.

Shall we just pull these stamps out?
It confused someone today that there was no 1.0 badge shown, and they assumed StatsBase was broken for 1.0

**Comment by nalimilan** [comment]
Yeah it's quite broken currently. Anyway I'd remove all Julia versions before 1.0.

**Comment by nalimilan** [comment]
This doesn't sound relevant anymore as it doesn't seem badges are going to work again.

**Comment by nalimilan** [comment]
https://github.com/JuliaStats/StatsBase.jl/pull/525 removes the badges.

**Pull request closed without merging**
