### PR TITLE
added Jensen-Shannon divergence

### PR DESCRIPTION
**Pull request by nash1111**
added Jensen-Shannon divergence,
i'll add some other functions like mutual information later

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. I think the plan is to remove distance/divergence functions from StatsBase as they are defined in Distances.jl already. Would you open a PR there? Please also add tests and include the new function in the docs.

**Comment by nalimilan** [comment]
Actually it seems `js_divergence` already exists in Distances.jl. :-/

**Comment by nalimilan** [comment]
Should this be closed then?

**Comment by nash1111** [comment]
yes, sorry for late reply

**Pull request closed without merging**
