### PR TITLE
Improve printing CoefTable

### PR DESCRIPTION
**Pull request by nalimilan**
Rely on printing code from Base to align numbers on the decimal separator. Unfortunately, we cannot treat column names as a normal row since names would be left-aligned with the decimal separator, which wastes space and is less clean. Instead, adjust the alignment manually so that columns are wide enough to contain names.

Only convert values to `PValue` before printing, so that users can still access the contents of columns as normal numbers. This is convenient in particular for testing in packages.

Before:
```
     Estimate Comments df      p
x1     1.4567     Good  1 0.1200
x2   -552.457    Great 56 0.3467
x3       44.5      Bad  2 <1e-15
```
After:
```
     Estimate  Comments  df       p
x1     1.4567     Good    1  0.1200
x2  -552.457      Great  56  0.3467
x3    44.5        Bad     2  <1e-15
```

Closes https://github.com/JuliaStats/StatsBase.jl/issues/378 by making `PValue` a purely internal type.

### CODE REVIEW

**Comment by nalimilan** [comment]
While I'm at it, what's your opinion about adding borders to the table, like we do for data frames? It could make large tables easier to read.

Before:
```
              Estimate Std. Error   z value Pr(>|z|)  Lower 95%  Upper 95%
(Intercept)  2.88645     0.227144 12.7076     <1e-36  2.44125    3.33164
Eth: N      -0.567515    0.152449 -3.72265    0.0002 -0.86631   -0.26872
Sex: M       0.0870771   0.159025  0.547568   0.5840 -0.224606   0.398761
Age: F1     -0.445076    0.239087 -1.86157    0.0627 -0.913678   0.0235251
Age: F2      0.0927999   0.234502  0.395731   0.6923 -0.366816   0.552416
Age: F3      0.359485    0.246586  1.45785    0.1449 -0.123814   0.842784
Lrn: SL      0.296768    0.185934  1.59609    0.1105 -0.0676559  0.661191
```
After (doesn't render correctly on GitHub):
```
            │   Estimate │ Std. Error │   z value │ Pr(>|z|) │  Lower 95% │  Upper 95%
────────────┼────────────┼────────────┼───────────┼──────────┼────────────┼───────────
(Intercept) │  2.88645   │   0.227144 │ 12.7076   │   <1e-36 │  2.44125   │  3.33164
Eth: N      │ -0.567515  │   0.152449 │ -3.72265  │   0.0002 │ -0.86631   │ -0.26872
Sex: M      │  0.0870771 │   0.159025 │  0.547568 │   0.5840 │ -0.224606  │  0.398761
Age: F1     │ -0.445076  │   0.239087 │ -1.86157  │   0.0627 │ -0.913678  │  0.0235251
Age: F2     │  0.0927999 │   0.234502 │  0.395731 │   0.6923 │ -0.366816  │  0.552416
Age: F3     │  0.359485  │   0.246586 │  1.45785  │   0.1449 │ -0.123814  │  0.842784
Lrn: SL     │  0.296768  │   0.185934 │  1.59609  │   0.1105 │ -0.0676559 │  0.661191
```

**Comment by ararslan** [comment]
> doesn't render correctly on GitHub

Renders fine for me, and +1 for the borders.

**Comment by nalimilan** [comment]
OK. Variant with borders on the sides (same thing as data frames):
```
│             │   Estimate │ Std. Error │   z value │ Pr(>|z|) │  Lower 95% │  Upper 95% │
├─────────────┼────────────┼────────────┼───────────┼──────────┼────────────┼────────────┤
│ (Intercept) │  2.88645   │   0.227144 │ 12.7076   │   <1e-36 │  2.44125   │  3.33164   │
│ Eth: N      │ -0.567515  │   0.152449 │ -3.72265  │   0.0002 │ -0.86631   │ -0.26872   │
│ Sex: M      │  0.0870771 │   0.159025 │  0.547568 │   0.5840 │ -0.224606  │  0.398761  │
│ Age: F1     │ -0.445076  │   0.239087 │ -1.86157  │   0.0627 │ -0.913678  │  0.0235251 │
│ Age: F2     │  0.0927999 │   0.234502 │  0.395731 │   0.6923 │ -0.366816  │  0.552416  │
│ Age: F3     │  0.359485  │   0.246586 │  1.45785  │   0.1449 │ -0.123814  │  0.842784  │
│ Lrn: SL     │  0.296768  │   0.185934 │  1.59609  │   0.1105 │ -0.0676559 │  0.661191  │
```
And with borders above and below (which would make the separation clearer once we add fit statistics like R², nobs) :
```
┌─────────────┬────────────┬────────────┬───────────┬──────────┬────────────┬────────────┐
│             │   Estimate │ Std. Error │   z value │ Pr(>|z|) │  Lower 95% │  Upper 95% │
├─────────────┼────────────┼────────────┼───────────┼──────────┼────────────┼────────────┤
│ (Intercept) │  2.88645   │   0.227144 │ 12.7076   │   <1e-36 │  2.44125   │  3.33164   │
│ Eth: N      │ -0.567515  │   0.152449 │ -3.72265  │   0.0002 │ -0.86631   │ -0.26872   │
│ Sex: M      │  0.0870771 │   0.159025 │  0.547568 │   0.5840 │ -0.224606  │  0.398761  │
│ Age: F1     │ -0.445076  │   0.239087 │ -1.86157  │   0.0627 │ -0.913678  │  0.0235251 │
│ Age: F2     │  0.0927999 │   0.234502 │  0.395731 │   0.6923 │ -0.366816  │  0.552416  │
│ Age: F3     │  0.359485  │   0.246586 │  1.45785  │   0.1449 │ -0.123814  │  0.842784  │
│ Lrn: SL     │  0.296768  │   0.185934 │  1.59609  │   0.1105 │ -0.0676559 │  0.661191  │
└─────────────┴────────────┴────────────┴───────────┴──────────┴────────────┴────────────┘
```
We could also limit the number of decimals used for the z-value (like statsmodels.org and Stata do), since they never matter.

**Comment by nalimilan** [comment]
And a lighter variant:
```
┌──────────────────────────────────────────────────────────────────────────────────┐
│              Estimate    Std. Error    z value  Pr(>|z|)   Lower 95%   Upper 95% │
├──────────────────────────────────────────────────────────────────────────────────┤
│ (Intercept)   2.88645      0.227144  12.7076      <1e-36   2.44125     3.33164   │
│ Eth: N       -0.567515     0.152449  -3.72265     0.0002  -0.86631    -0.26872   │
│ Sex: M        0.0870771    0.159025   0.547568    0.5840  -0.224606    0.398761  │
│ Age: F1      -0.445076     0.239087  -1.86157     0.0627  -0.913678    0.0235251 │
│ Age: F2       0.0927999    0.234502   0.395731    0.6923  -0.366816    0.552416  │
│ Age: F3       0.359485     0.246586   1.45785     0.1449  -0.123814    0.842784  │
│ Lrn: SL       0.296768     0.185934   1.59609     0.1105  -0.0676559   0.661191  │
└──────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by ararslan** [comment]
A difference in printing from `DataFrame`s would be worthwhile I think.

**Comment by nalimilan** [comment]
Maybe this?
```
              ┌────────────┬────────────┬───────────┬──────────┬────────────┬────────────┐
              │   Estimate │ Std. Error │   z value │ Pr(>|z|) │  Lower 95% │  Upper 95% │
┌─────────────┼────────────┼────────────┼───────────┼──────────┼────────────┼────────────┤
│ (Intercept) │  2.88645   │   0.227144 │ 12.7076   │   <1e-36 │  2.44125   │  3.33164   │
│ Eth: N      │ -0.567515  │   0.152449 │ -3.72265  │   0.0002 │ -0.86631   │ -0.26872   │
│ Sex: M      │  0.0870771 │   0.159025 │  0.547568 │   0.5840 │ -0.224606  │  0.398761  │
│ Age: F1     │ -0.445076  │   0.239087 │ -1.86157  │   0.0627 │ -0.913678  │  0.0235251 │
│ Age: F2     │  0.0927999 │   0.234502 │  0.395731 │   0.6923 │ -0.366816  │  0.552416  │
│ Age: F3     │  0.359485  │   0.246586 │  1.45785  │   0.1449 │ -0.123814  │  0.842784  │
│ Lrn: SL     │  0.296768  │   0.185934 │  1.59609  │   0.1105 │ -0.0676559 │  0.661191  │
└─────────────┴────────────┴────────────┴───────────┴──────────┴────────────┴────────────┘
```

**Comment by ararslan** [comment]
How do DataFrames print again, for reference?

**Comment by nalimilan** [comment]
Like this:
```
│ Row │ x1       │ x2        │
│     │ Float64  │ Float64   │
├─────┼──────────┼───────────┤
│ 1   │ 0.417064 │ 0.255012  │
│ 2   │ 0.774886 │ 0.188739  │
│ 3   │ 0.8007   │ 0.0210281 │
```

**Comment by ararslan** [comment]
Okay thanks. I think my favorite thus far is what you called the lighter variant.

**Comment by pdeffebach** [comment]
If we print names with spaces at the top, we need to think of how the user will index the table intuitively.

**Comment by pdeffebach** [comment]
Is this the same as the printing of a regression in DataFrames based on data I had open just now 

```

. reg healthatwork  age male  self_days12months fac_days12months

      Source |       SS           df       MS      Number of obs   =       331
-------------+----------------------------------   F(4, 326)       =      6.46
       Model |  35.0468222         4  8.76170556   Prob > F        =    0.0001
    Residual |  441.950157       326  1.35567533   R-squared       =    0.0735
-------------+----------------------------------   Adj R-squared   =    0.0621
       Total |  476.996979       330  1.44544539   Root MSE        =    1.1643

-----------------------------------------------------------------------------------
     healthatwork |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
------------------+----------------------------------------------------------------
        age_preg1 |  -.0151378   .0147566    -1.03   0.306    -.0441679    .0138923
     male_above15 |  -.0636461   .0691374    -0.92   0.358    -.1996579    .0723656
self_days12months |  -.0017748   .0005313    -3.34   0.001    -.0028199   -.0007296
 fac_days12months |  -.0031908    .000801    -3.98   0.000    -.0047666   -.0016149
            _cons |   4.600398   .3359493    13.69   0.000     3.939496      5.2613
-----------------------------------------------------------------------------------
```

I think this proposal is really good. However it would be nice if we could also print the summary statistics at the top like R-squared, N, and an F-test.  This should probably another method that is added to the printing of the `model` struct.

I think `Lower 95%` and `Upper 95%` might be confusing. It makes me think of `5%` and `95%` instead of `2.5%` and `97.5%`.

**Comment by nalimilan** [comment]
> Is this the same as the printing of a regression in DataFrames based on data I had open just now

Not sure what you mean?

> I think this proposal is really good. However it would be nice if we could also print the summary statistics at the top like R-squared, N, and an F-test. This should probably another method that is added to the printing of the `model` struct.

See https://github.com/JuliaStats/StatsBase.jl/pull/119. Better keep that discussion separate I think.

> I think `Lower 95%` and `Upper 95%` might be confusing. It makes me think of `5%` and `95%` instead of `2.5%` and `97.5%`.

Yeah, maybe. I took the formulation from FixedEffectsModels. Anyway the terms are chosen by modeling packages, so let's discuss that at https://github.com/JuliaStats/GLM.jl/pull/299.

**Comment by nalimilan** [comment]
OK, last choice between two lighter variants. Do you prefer this:
```
┌──────────────────────────────────────────────────────────────────────────────────┐
│                Estimate  Std. Error    z value  Pr(>|z|)   Lower 95%   Upper 95% │
├──────────────────────────────────────────────────────────────────────────────────┤
│ (Intercept)   2.88645      0.227144  12.7076      <1e-36   2.44125     3.33164   │
│ Eth: N       -0.567515     0.152449  -3.72265     0.0002  -0.86631    -0.26872   │
│ Sex: M        0.0870771    0.159025   0.547568    0.5840  -0.224606    0.398761  │
│ Age: F1      -0.445076     0.239087  -1.86157     0.0627  -0.913678    0.0235251 │
│ Age: F2       0.0927999    0.234502   0.395731    0.6923  -0.366816    0.552416  │
│ Age: F3       0.359485     0.246586   1.45785     0.1449  -0.123814    0.842784  │
│ Lrn: SL       0.296768     0.185934   1.59609     0.1105  -0.0676559   0.661191  │
└──────────────────────────────────────────────────────────────────────────────────┘
```

or this?
```
 ────────────────────────────────────────────────────────────────────────────────
                Estimate  Std. Error    z value  Pr(>|z|)   Lower 95%   Upper 95%
 ────────────────────────────────────────────────────────────────────────────────
 (Intercept)   2.88645      0.227144  12.7076      <1e-36   2.44125     3.33164
 Eth: N       -0.567515     0.152449  -3.72265     0.0002  -0.86631    -0.26872
 Sex: M        0.0870771    0.159025   0.547568    0.5840  -0.224606    0.398761
 Age: F1      -0.445076     0.239087  -1.86157     0.0627  -0.913678    0.0235251
 Age: F2       0.0927999    0.234502   0.395731    0.6923  -0.366816    0.552416
 Age: F3       0.359485     0.246586   1.45785     0.1449  -0.123814    0.842784
 Lrn: SL       0.296768     0.185934   1.59609     0.1105  -0.0676559   0.661191
 ────────────────────────────────────────────────────────────────────────────────
```

**Comment by ararslan** [comment]
Ooh, tough choice. Aesthetically I think I prefer the latter, but there's also the question of what it looks like if it gets wrapped by e.g. being printed in a narrow terminal. I imagine that having the side "walls" could make it easier to see what's happening in that case, though that's just speculation.

**Comment by mschauer** [comment]
https://inf.ethz.ch/personal/markusp/teaching/guides/guide-tables.pdf suggest bottom one.

**Comment by nalimilan** [comment]
OK, I've pushed a commit implementing the lighter lighter variant.

**Comment by mschauer** [comment]
Is it difficult to fix the alignment of the headers?

**Comment by nalimilan** [comment]
Which ones?

**Comment by mschauer** [comment]
`Estimate` and `z value` one to the left (aligned with the digit before and not with the decimal point).

**Comment by nalimilan** [comment]
Actually they are aligned on the right. That would be clearer if the numbers were padded with zeros. I think that's what your links recommend, right?

**Comment by mschauer** [comment]
Ok, I get it. That will do I think.

**Pull request merged**
