### PR TITLE
Add level argument to confint

### PR DESCRIPTION
**Pull request by nalimilan**
Fixes https://github.com/JuliaStats/GLM.jl/issues/241.

### CODE REVIEW

**Comment by nalimilan** [comment]
OK to merge?

**Comment by lbittarello** [comment]
Why not add a similar argument to `coeftable`?

**Comment by nalimilan** [comment]
Good idea. I see you implemented a `level` keyword argument in Microeconometrics. Two questions:
- Wouldn't it be clearer to call it `confint`, since in the context of `coeftable` nothing indicates that it applies to a confidence interval?
- Should `confint` take a keyword argument too rather than a positional argument (as is currently the case in GLM, but undocumented)?

**Comment by lbittarello** [comment]
> Wouldn't it be clearer to call it `confint`, since in the context of `coeftable` nothing indicates that it applies to a confidence interval?

I don't have a strong preference. On the one hand, `confint` is marginally clearer. On the other hand, `level` can't refer to anything else in this context. I used `level` because Stata does so. Another option is `cilevel`.

> Should `confint` take a keyword argument too rather than a positional argument (as is currently the case in GLM, but undocumented)?

I like keywords. `r2` uses a positional argument though, so it might be better to be consistent.

**Comment by nalimilan** [comment]
OK, I've switched to keyword arguments, and added it to `coeftable`. Since keyword arguments don't participate in dispatch, the default cannot be set in the generic method, and needs to be defined by each implementation. So this is now purely a doc PR.

Good to merge?

**Pull request merged**
